import A_a_Identification_source_as_video_input_picture
import A_b_Identification_source_as_video_input_video
import A_c_Identification_source_as_picture_folder_input_picture
import B_Live_recognition
import C_Automation_for_routine_identification
